//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zal.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Zal.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PKպ�V�^J;�+DiskInfo.exe�|{\T�����a��)v0�(,�5�C�A)��KbZb�Q�q�P��V:ˮ���)K���FQ�@E˼u��/���~��Y{�����￟�����]�g={�g�=SJ� a�_Q�R���B��A��_-|�}��!�Wd��}8&gt;���&lt;4s~���&lt;��=��/��� �9~B��f�3�b�LP����[�QZo��P�4�������5���2�wzv���nݚx����o�gҰ3�f���l^yͰ��������߈�z�ϝ���im�L��K�	��~{�&amp;k��B�f�&gt;�H�[X� �iN�
        ///B8���&lt;�:5��� �_�%�]�N�`/�a����U�Bc/����$!.Ӑ&amp;���W�����l��S���/Z(�����ɻ� ��&apos;��=�3&amp;^��&lt;4{f�LA�z&apos;����y�b�a��!&amp;��J��BG�Rl �7$����Va9&lt;�u��g��td9 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DiskInfo {
            get {
                return ResourceManager.GetString("DiskInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MZ����@��	�!�L�!This program cannot be run in DOS mode.        ///
        ///$;Zf;f5;f5;f5�Ie4z;f5�Ic4�;f5�Ib4t;f5�Ig4|;f5�Eb4o;f5�Ee4u;f5�Ec4@;f5;g5�;f5kDo4p;f5kD�5~;f5kDd4~;f5Rich;f5PEd����d�&quot;$��&gt;@@`�p( ��450	�pG@0�$k� [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string presentmon {
            get {
                return ResourceManager.GetString("presentmon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///  {
        ///    &quot;Name&quot;: &quot;Application Frame Host&quot;,
        ///    &quot;DisplayName&quot;: null,
        ///    &quot;IsBlacklisted&quot;: true
        ///  },
        ///  {
        ///    &quot;Name&quot;: &quot;Microsoft.Media.Player&quot;,
        ///    &quot;DisplayName&quot;: null,
        ///    &quot;IsBlacklisted&quot;: true
        ///  },
        ///  {
        ///    &quot;Name&quot;: &quot;Settings&quot;,
        ///    &quot;DisplayName&quot;: null,
        ///    &quot;IsBlacklisted&quot;: true
        ///  },
        ///  {
        ///    &quot;Name&quot;: &quot;Calculator&quot;,
        ///    &quot;DisplayName&quot;: null,
        ///    &quot;IsBlacklisted&quot;: true
        ///  },
        ///  {
        ///    &quot;Name&quot;: &quot;ReShade_Setup_4.9.1&quot;,
        ///    &quot;DisplayName&quot;: null,
        ///    &quot;IsBlacklisted&quot;: true
        ///  },
        ///  {
        ///    &quot;Name&quot;: &quot;Syste [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Processes {
            get {
                return ResourceManager.GetString("Processes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MZ����@H��	�!�L�!This program cannot be run in DOS mode.        ///
        ///$MA��	 ä	 ä	 äBX�� äBXƥ� äBXǥ: ä�&gt;� ä�ǥ ä��� ä�ƥ` ä	 ä( äB��� äB�ƥ�%äB�ǥ�$äBXť äBX¥ ä	 ¤�!äB�ʥ
        /// äB�å äB�&lt;� ä	 T� äB��� äRich	 äPEd�qdg�&quot;)U�_��O@�`����k���q��x*��X����7�XpX(�X [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string server {
            get {
                return ResourceManager.GetString("server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] white {
            get {
                object obj = ResourceManager.GetObject("white", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
